on: [push, workflow_dispatch]
jobs:
  deploy:
    permissions:
      id-token: write
      contents: read
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - uses: actions/setup-node@v2
        with:
          node-version: "20"
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::${{secrets.AWS_ACCOUNT_ID}}:role/gh-actions-role
          aws-region: us-east-1
      - id: install-aws-cli
        uses: unfor19/install-aws-cli-action@v1
        with:
          version: 2                         # default
          verbose: false                     # default
          arch: amd64                        # allowed values: amd64, arm64
      - name: Deploy with CloudFormation
        id: cfn-stack
        uses: aws-actions/aws-cloudformation-github-deploy@v1
        with:
          name: cloudformation
          template: stack.yml
          no-fail-on-empty-changeset: "1"
          parameter-overrides: >-
            Environment=beta
